apiVersion: v1
kind: Pod
metadata:
  name: test-connection
  labels:
    app: {{ .Release.Name }}
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["curl"]
      args: ["http://{{ .Release.Name }}:{{ .Values.service.port }}"]
  restartPolicy: Never
